### PR TITLE
Development

### PR DESCRIPTION
**Pull request by EmirVatric**

### CODE REVIEW

**Comment by JamesOkunlade** [comment]
# James on it.

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hello @EmirVatric  and @SamuelC28,

Welcome to the Ruby section and nice job doing your first Ruby project.

Your `bubblesort` method works well but your `bubblesortby` method does not pass our test suite. Apparently, it's not sorting unsorted arrays.

You should make your code less complex by simply writing the methods rather than putting them in a class for now. You won't need to instantiate or add any test array. Simply write the methods and we'll test with our test suite. 

Please work on the `bubblesortby` method again and submit for a re-review.

Happy coding!

**Comment by mcrd25** [comment]
# Currently under review

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Still some work to do! 😢 

Hi @EmirVatric  and @SamuelC28 
Your bubble_sort_by method is still failing tests, do you need some extra guidance here?

Tips 💡 

- you do not need to change completely your approach from `bubble_sort`, you simply need to implement a swap
- your `bubble_sort_by` method is not returning anything but `puts`, needs to return the sorted array\
- As it stands though your logic is correct, but you not returning the array
- Also please try to have clean code, with 2 space indentation according to ruby standards, the indentation is a bit off 😅 

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

**Comment by JamesOkunlade** [comment]
## James on it.

**Review by JamesOkunlade — APPROVED** [review]
Really great job so far. You meet all the basic requirements now.

It's a :+1: from me. Go ahead and merge.

Good luck with your future projects.

**Comment by mcrd25** [comment]
Congrats @EmirVatric and @SamuelC28 lad you guys got it to pass 😄

**Pull request merged**
